apiVersion: v1
kind: Service
metadata:
  labels:
    name: tomcat8
  name: tomcat8
spec:
  ports:
    # the port that this service should serve on
    - port: 8083
      targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: tomcat8
  sessionAffinity: ClientIP
  publicIPs:
    - 192.168.1.66
